title: Vincent Klaiber
description: Developer from Sweden. Teching web development at Yrgo. Open-source entusiast at GitHub. Sharing links on Twitter.

author:
  name: Vincent Klaiber
  picture: https://github.com/vinkla.png
  twitter: vinkla

twitter:
  username: vinkla

logo: https://github.com/vinkla.png

google_site_verification: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI

permalink: /:year/:title/

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
  style: compressed
  sass_dir: assets/styles

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
