title: Vincent Klaiber
description: Full stack development teacher at Yrgo. Open-source entusiast at GitHub. Sharing links on Twitter.
url: https://vinkla.com

author:
  name: Vincent Klaiber
  picture: https://avatars2.githubusercontent.com/u/499192
  twitter: vinkla

twitter:
  username: vinkla

logo: https://avatars2.githubusercontent.com/u/499192

social:
  links:
      - https://github.com/vinkla
      - https://keybase.io/vinkla
      - https://twitter.com/vinkla

google_site_verification: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI

permalink: /:year/:title/

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
  style: compressed
  sass_dir: assets/styles

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
