title: Vincent Klaiber
description: I'm Vincent and I work as a web developer in Gothenburg, Sweden.
url: https://vinkla.com
author:
  name: Vincent Klaiber
  picture: https://github.com/vinkla.png
  twitter: vnkla

twitter:
  username: vnkla

logo: https://github.com/vinkla.png

google_site_verification: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI

permalink: /:year/:title/

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
  style: compressed
  sass_dir: assets/styles

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
