title: Vincent Klaiber
description: Hello there, my name is Vincent Klaiber and I work as a web developer in Gothenburg, Sweden.
url: https://vinkla.com
author: Vincent Klaiber

twitter:
  username: vnkla

logo: https://github.com/vinkla.png

google_site_verification: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
