title: Vincent Klaiber
description: I'm Vincent and I work as a web developer in Gothenburg, Sweden.
url: https://vinkla.com
image: https://github.com/vinkla.png
author: Vincent Klaiber

twitter:
  username: vnkla

logo: https://github.com/vinkla.png

google_site_verification: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI

permalink: /:year/:title/

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
  style: compressed

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
